name: Install Hugo
description: Instalation of Hugo CLI
runs:
  using: "composite"
  steps:
    - name: Install Hugo CLI
      env:
        HUGO_VERSION: 0.139.3
      shell: bash
      run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      
